version: "3.7"
services:
  apd_service:
    build: .
    container_name: apd_container
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  app:
    build:
      context: .
    volumes:
      - .:/app  
